# Generated by Django 4.1.4 on 2023-01-13 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobList_title', models.CharField(max_length=200)),
                ('jobList_companyName', models.CharField(max_length=200)),
                ('jobList_location', models.CharField(max_length=200)),
                ('jobList_hire', models.IntegerField()),
                ('jobList_type', models.CharField(max_length=200)),
                ('jobList_experience', models.CharField(max_length=200)),
                ('jobList_industry', models.CharField(max_length=200)),
                ('jobList_preferredApplicant', models.CharField(max_length=100)),
                ('jobList_requiredLanguage', models.CharField(max_length=200)),
                ('jobList_deadline', models.CharField(max_length=100)),
                ('jobList_image_banner', models.ImageField(default='static/banner/employer_profile_cover.jpg', max_length=200, upload_to='static/banner/bannerUpload')),
                ('jobList_image_logo', models.ImageField(default='static/logo/hrinc_sq_logo.jpg', max_length=200, upload_to='static/logo/logoUpload')),
                ('jobList_summary', models.TextField(blank=True, max_length=300, null=True)),
                ('jobList_responsibility', models.TextField(blank=True, null=True)),
                ('jobList_qualification', models.TextField(blank=True, null=True)),
                ('jobList_qualification_Education', models.TextField(blank=True, null=True)),
                ('jobList_qualification_Experiences', models.TextField(blank=True, null=True)),
                ('jobList_qualification_other_requirements', models.TextField(blank=True, null=True)),
                ('jobList_user_name', models.CharField(max_length=200)),
                ('jobList_user_title', models.CharField(max_length=200)),
                ('jobList_user_phoneNumber', models.CharField(blank=True, max_length=200, null=True)),
                ('jobList_user_email', models.CharField(max_length=200)),
                ('jobList_user_address', models.CharField(max_length=200)),
                ('jobList_jobFunction', models.ManyToManyField(to='jobsite.jobfunction')),
            ],
        ),
    ]
