# Generated by Django 4.1.4 on 2023-01-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsite', '0002_joblist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblist',
            name='jobList_image_banner',
            field=models.ImageField(default='employer_profile_cover.jpg', max_length=200, upload_to=''),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='jobList_image_logo',
            field=models.ImageField(default='hrinc_sq_logo.jpg', max_length=200, upload_to=''),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='jobList_jobFunction',
            field=models.ManyToManyField(related_name='jobList_jobFunction', to='jobsite.jobfunction'),
        ),
    ]
